# Generated by Django 3.0.6 on 2020-06-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200603_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title_pic',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
